export const table = {
  components: {
    contactForm: {
      title: "Get in touch",
      subtitle: "Feel free to contact us.",
      fullName: "Full name",
      email: "Email",
      message: "Message",
      send: "Send message",
      sentSuccessfully: "Message sent successfully.",
      notSent: "Message not sent. Try again.",
      nameRequired: "Name required",
      emailRequired: "Email required",
      invalidEmail: "Invalid email address",
      messageRequired: "Message required",
      captchaRequired: "Verification required",
    },
    cta: {
      title: "Join us today.",
      subtitle: "Get more income from your traffic 😉",
    },
    hero: {
      title: "Let's make money together 🤑",
      subtitle: "Join our fast-growing casino and earn up to 50% commission.",
    },
    whyUs: {
      title: "Why partner up with Red Affiliates?",
      one: {
        title: "We are here for you",
        subtitle:
          "An open minded team, listening to its partners' needs. Your success is our goal.",
      },
      two: {
        title: "High conversion and customer retention",
        subtitle:
          "We do our best to convert your traffic into players. The casino reward system means great retention and high player lifetime values.",
      },
      three: {
        title: "Quick payouts",
        subtitle:
          "We pay all commission by the 15th of each month and offer a range of payment methods to suits our affiliates needs, from Neteller, Skrill, Bitcoin to wire transfers.",
      },
    },
    faq: {
      title: "Frequently asked questions",
      one: {
        title: "How do I sign up?",
        subtitle:
          "Complete the registration form, we’ll validate your account and welcome you as our affiliate.",
      },
      two: {
        title: "How do I get paid?",
        subtitle:
          "You can get paid via Bank Transfer (IBAN account), Bitcoin, Skrill or Neteller.",
      },
      three: {
        title: "When do I get paid?",
        subtitle:
          "We will transfer the commission by the 15th of each month. If the amount is lower than €50 (€300 for a bank transfer) it will not be payed out but transferred to the next months payout.",
      },
      four: {
        title: "How often are my statistics updated?",
        subtitle: "Statistics are updated every hour.",
      },
      five: {
        title: "Terms and conditions?",
        subtitle:
          '<a href="/terms-and-conditions" class="link">Click here</a> to read our terms and conditions',
      },
      six: {
        title: "What if I have more questions?",
        subtitle:
          'Our team is always happy to answer any questions you may have, so just drop us a line at <a class="link" href="mailto:partners@red-affiliates.com">partners@red-affiliates.com</a>',
      },
    },
    commission: {
      subtitle:
        "You will earn lifetime revenue share on all the traffic that you refer to us.",
      title: "No negative carryover. Lifetime revenue share.",
      one: {
        title: "Revenue share",
        subtitle:
          "You earn a percentage of the NGR generated by your referred players. NGR = Total revenue - Issued bonuses - Admin fee (30%).",
      },
      two: {
        title: "CPA",
        subtitle:
          "You earn a flat rate on each new player you refer, who meets the requirements indicated in the deal plan we agree. Get in touch with your Affiliate Manager to discuss a CPA deal.",
      },
      three: {
        title: "Hybrid",
        subtitle:
          "Hybrid deals are customized to combine RevShare and CPA. For websites that generate targeted traffic, it is in our interest to meet your needs to the fullest extent. Get in touch with your Affiliate Manager to discuss a Hybrid deal.",
      },
      four: {
        title: "Sub-affiliates",
        subtitle:
          "If you introduce another affiliate, you will receive a 5% sub-affiliate commission on that player's NGR.",
      },
    },
    about: {
      title: "Promote the brand that converts",
      subtitle: "RED PingWin is a fast-growing real money and bitcoin casino.",
      one: {
        title: "Live Chat Support",
        subtitle: "24/7",
      },
      two: {
        title: "Casino Games",
        subtitle: "3,000+",
      },
      three: {
        title: "Established",
        subtitle: "2017",
      },
      license: "Licence",
      curacao: "Curacao",
      software: "Software",
      payments: "Payments",
      languages: "Languages",
      currencies: "Currencies",
      visitCasino: "Visit casino",
    },
    termsAndConditions: {
      title: "AFFILIATE TERMS & CONDITIONS",
      firstText:
        'This is an agreement (“The Affiliate Agreement”) between you (“you” or “Affiliate”) and red-affiliates.com (“Company”, “us”, “we” or "Affiliate Program"). Payment services are accomplished by Dama N.V. on behalf of red-affiliates.com.',
      secondText:
        "By registering for the Affiliate Program, and by accessing and using any of our marketing tools or accepting any reward, bonus or commission, whether contained in the Affiliate Agreement or elsewhere as a part of our Affiliate Program, you will be deemed to have read, understood and agreed with each paragraph of this Affiliate Agreement.",
      thirdText:
        "We may periodically make modifications to this Agreement. While we will do our best to notify you of such changes, we recommend that you revisit this page regularly. Your continued use of the Affiliate Program will constitute your consent to the updated Agreement.",
      one: {
        title: "1. DEFINITIONS",
        firstText:
          "1.1 “Affiliate” means you, the person or entity, who applies to participate or register in the Affiliate Program.",
        secondText:
          "1.2 “Affiliate Account” means the account of the Affiliate set up after an Affiliate Application is made by the Affiliate to take part in the Affiliate Program and approved by Company or created immediately after registration.",
        thirdText:
          "1.3 “Affiliate Agreement” (a) means all the terms and conditions set out in this document, (b) the terms and conditions of the Commission Structures applicable to the different products and brands, and (c) any other rules or guidelines of the Company and/or Websites made known to the Affiliate from time to time.",
        fourthText:
          "1.4 “Affiliate Application” means the application made by the Affiliate to participate in the Affiliate Program. Relevant if the registration is currently closed and requires confirmation by the administration. If the registration is open at the moment, the partner has access to the personal cabinet immediately after registration and the opportunity to earn money.",
        fifthText:
          "1.5 “Affiliate Links” means internet hyperlinks used by the Affiliate to link from the Affiliate Website(s) or any other any third party website or other sources to Company Websites.",
        sixthText:
          "1.6 “Affiliate Program” means collaboration between the Company and the Affiliate whereby the Affiliate promotes the Company’s websites and creates Affiliate Links from the Affiliate Website(s) to Company’s websites. For such services the Affiliate is paid a commission depending on the generated traffic to the Company’s websites, subject to terms within this Affiliate Agreement and to the applicable product-specific Commission Structure.",
        seventhText:
          "1.7 “Affiliate Wallet” means an online wallet in the name of the Affiliate into which Company pays the commission and any other payments due to the Affiliate, which the Affiliate can withdraw in accordance with the Affiliate Agreement;",
        eighthText:
          "1.8 “Affiliate Website” means any website which is maintained, operated or otherwise controlled by the Affiliate.",
        ninthText:
          "1.9 “Company Websites” means the website www.redping.win or other such websites (including mirror websites) as may be added to this Affiliate Program from time to time.",
        tenthText:
          "1.10 “Customer” it’s the person who correctly went through procedures of registration on Company’s website using Affiliate Link.",
        eleventhText:
          "1.11 “New Depositor” means a new, first-time customer of the Company who made a first deposit at Company’s Websites player account, in accordance with the applicable terms and conditions of Company’s Websites. This excludes the Affiliate, its employees, relatives and friends.",
        twelfthText:
          "1.12 “Depositor” is the person who makes one or more that one deposit’s at Company’s Websites.",
        thirteenthText:
          "1.13 “Commission” means the percentage of the Net Gaming Revenue, or, where applicable, a fixed amount for a New Depositor (CPA structure) or consisting of several parts (Hybrid) as set out in the Commission Structures.",
        fourteenthText:
          "1.14 “Commission Structures” means any specific reward structures expressly agreed between Company and the Affiliate.",
        fifteenthText:
          "1.15 “Confidential Information” means any information of commercial or essential value relating to Company such as, but not limited to, financial reports, trade secrets, know-how, prices and custom quotes, business information, products, strategies, databases, technology, information about Customers, other customers and users of Company Websites, marketing plans and manners of operation.",
        sixteenthText:
          "1.16 “Intellectual Property Rights” means any copyrights, trademarks, service marks, domain names, brands, business names, and registrations of the aforesaid and/or any other similar rights of this nature.",
        seventeenthText:
          "1.17 “Net Gaming Revenue” or “NGR” means all monies received by Company from Customers as placed bets, less (a) winnings returned to Customers, (b) issued bonuses, (c) net balance corrections, (d) administration fees, (e) fraud costs and chargebacks. For the avoidance of doubt, all Net Gaming Revenue amounts mentioned above are only related to Customers referred to Company Websites by the Affiliate Website(s).",
        eighteenthText:
          "1.18 “Parties” means Company and the Affiliate (each a “Party”).",
        nineteenthText:
          "1.19 “Personal Data” means any information relating to any person, whether individual or legal that is or may be identified, directly or indirectly.",
        twentiethText:
          "1.20. Sub-affiliate is the person who got registered through Affiliate Link and start to work as an Affiliate with Affiliate Program.",
      },
      two: {
        title: "2. AFFILIATE OBLIGATIONS",
        first: {
          title: "2.1 Registering as Affiliate",
          text:
            "To become a member of our Affiliate Program you must accept these terms and conditions by ticking the respective box while submitting the Affiliate Application. The Affiliate Application will form an integral part of the Affiliate Agreement.",
        },
        second: {
          title: "2.2 Affiliate login details",
          text:
            "It is your sole obligation and responsibility to ensure that login details for your Affiliate Account are kept confidential and secure at all times. Any unauthorised use of your Affiliate Account resulting from your failure to adequately guard your login information shall be your sole responsibility, and you remain solely responsible and liable for all such activity occurring under your Affiliate Account user ID and password (whether such activity was undertaken by you or not). It is your obligation to inform us immediately if you suspect illegal or unauthorised use of your Affiliate Account.",
        },
        third: {
          title: "2.3 Affiliate Program participation",
          text:
            "The Affiliate Program is intended for your direct participation. Opening an Affiliate Account for a third party, brokering or transfering an Affiliate Account is not accepted. Affiliates wishing to transfer an account to another beneficial owner must contact us and request permission. Besides, you shall not open more than one Affiliate Account without our prior written consent. By agreeing to participate in the Affiliate Program, you agree to use your best efforts to actively advertise, market and promote the Company Websites in accordance with the Affiliate Agreement and Company’s instructions from time to time. You will ensure that all activities taken by you under the Affiliate Agreement will be in Company’s best interest and will in no way harm the Company’s reputation or goodwill. You may link to the Company Website’s using the Affiliate Links or other such materials as we may from time to time approve. This is the only method by which you may advertise on our behalf.",
        },
        fourth: {
          title: "2.4 Affiliate Website",
          text:
            "You will be solely responsible for the development, operation and maintenance of the Affiliate Website and for all materials that appear on the Affiliate Website. You shall at all times ensure that the Affiliate Website is compliant with all applicable laws, including General Data Protection Regulation (GDPR), and functions as a professional website. You will not present the Affiliate Website in such a way so that it may cause confusion with the Company Websites, or so that it may give the impression that it is owned or operated by Company. The Affiliate Website will not contain any defamatory, libellous, discriminatory or otherwise unsuitable content (including, but not limited to, violent, obscene, derogatory or pornographic materials or content which would be unlawful in target country).",
        },
        fifth: {
          title: "2.5 Valid traffic and good faith",
          text:
            "You will not generate traffic to Company Websites by registering as a Customer whether directly or indirectly (for example by using associates, family members or other third parties). Such behaviour shall be deemed as fraud. You will also not attempt to benefit from traffic not generated in good faith. If you have any reasonable suspicion that any Customer referred by you is in any way associated to bonus abuse, money laundering, fraud, or other abuse of remote gaming websites, you will immediately notify us of this.",
        },
        sixth: {
          title: "2.6 Unsuitable websites",
          text:
            "You will not use any Affiliate Links or otherwise place any digital advertisements whatsoever featuring our Intellectual Property on any unsuitable websites (whether owned by a third party or otherwise). Unsuitable websites include, but are not limited to, websites that are aimed at children, display illegal pornography or other illegal sexual acts, promote violence, promote discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age, promote illegal activities or in any way violate the intellectual property rights of any third party or of the Company, or breach any relevant advertising regulations or codes of practice in any territory where such Affiliate Links or digital advertisements may be featured.",
        },
        seventh: {
          title: "2.7 Affiliate Links",
          text:
            "The Affiliate Links shall be displayed at least as prominently as any other sales link on the Affiliate Website. You will only use Affiliate Links provided by Company within the scope of the Affiliate Program.",
        },
        eighth: {
          title: "2.8 Email and SMS marketing",
          text:
            "If sending any emails or SMS communications to individuals which (a) include any of Company’s Intellectual Property Rights; or (b) otherwise intend to promote Company Websites, you must first obtain our permission to send such emails. If such permission is granted by the Company, you must then ensure you have each and every recipient’s explicit consent to receive marketing communications in the form of communication to be sent (i.e. by SMS or email) and that such individuals have not opted out of receiving such communication. You must also make it clear to the recipient that all marketing communications are sent from you and are not from our Company.",
        },
        ninth: {
          title: "2.9 Use of Company Intellectual Property Rights",
          text:
            "Any use of Company’s Intellectual Property Rights must be in accordance with any brand guidelines issued to you from time to time and are always subject to the approval required in clause below. You will not register domain names, as well as search terms or other identifiers for use in any search engine, portal, app store, sponsored advertising service or other referral service which are identical to any of the Company’s trademarks or otherwise include the Company trademarks.",
        },
        tenth: {
          title: "2.10 Approved creative",
          text:
            "You will not use any advertising layout or creative (including banners, images, logos) incorporating our Intellectual Property Rights unless the advertising layout or creative was provided to you by the Company or (if advertising layouts are created by you) without the advance written approval of Company. You will not modify the appearance of any advertising that has been provided to you or for which approval was granted. It is your responsibility to seek approval from Company in time for launch of any advertising campaign or creative, to ensure you have written approval from the Company in relation to advertising, and to be able to evidence such approval upon request.",
        },
        eleventh: {
          title: "2.11 Loyalty Programs",
          text:
            "You will not offer any cash-back / value-back or similar programs, other than such programs as are offered on the Company Websites.",
        },
        twelfth: {
          title: "2.12 Responsible Gaming",
          text:
            "The Company has ongoing commitment to responsible gaming and prevention of gambling addiction. You agree to actively cooperate with the Company to convey a responsible gaming message. Specifically, you will not use any material or in any way target persons who are under 18 or the legal gambling age in their jurisdiction.",
        },
        thirteenth: {
          title: "2.13 Illegal activity",
          text:
            "You will not target any territory or jurisdictions where gambling is illegal. You will act within the relevant and / or applicable law at all times and you will not perform any act which is illegal in relation to the Affiliate Program or otherwise.",
        },
        fourteenth: {
          title: "2.14 Data Protection and Cookies",
          text:
            "You shall at all times comply with the General Data Protection Regulation (GDPR) and any existing or new data protection acts, regulations or law applicable to your territory. This includes all applicable legislation and/or regulations relating to the use of ‘cookies’.",
        },
        fifteenth: {
          title: "2.15 Cost and expense",
          text:
            "You shall be solely responsible for all risk, costs and expenses incurred by you in meeting your obligations under the Affiliate Agreement.",
        },
        sixteenth: {
          title: "2.16 Company monitoring of Affiliate activity",
          text:
            "You will immediately give Company all such assistance as is required and provide us with all such information as is requested by Company to monitor your activity under the Affiliate Program.",
        },
        seventeenth: {
          title: "2.17 Commissions paid incorrectly",
          text:
            "The Affiliate agrees to immediately upon request by Company, return all Commissions received based on New Customers referred to Company in breach of the Affiliate Agreement or relating to fraudulent or falsified transactions.",
        },
      },
      three: {
        title: "3. AFFILIATE RIGHTS",
        first: {
          title: "3.1. Right to direct Customers",
          text:
            "We grant you the non-exclusive, non-assignable, right, during the term of this Affiliate Agreement, to direct Customers to such Company Websites as we have agreed with you in strict accordance with the terms of the Affiliate Agreement. You shall have no claim to Commission or other compensation on business secured by persons or entities other than you.",
        },
        second: {
          title: "3.2. License to use Company Intellectual Property Rights",
          text:
            "We grant to you a non-exclusive, non-transferable license, during the term of this Affiliate Agreement, to use the Company Intellectual Property Rights, which we may from time to time approve solely in connection with the display of the promotional materials on the Affiliate Website or in other such locations as may have been expressly approved (in writing) by Company. This license cannot be sub-licensed, assigned or otherwise transferred by you.",
        },
        third: {
          title: "3.3. Players’ Personal Data",
          text:
            "For the purpose of the services delivered under this Agreement, it is understood that the Affiliate shall not have access to any Personal Data of Company’s customers.",
        },
      },
      four: {
        title: "4. COMPANY OBLIGATIONS",
        firstText:
          "4.1. We shall use our best efforts to provide you with all materials and information required for necessary implementation of the Affiliate Links.",
        secondText:
          "4.2. At our sole discretion, we will register any Customers directed to the Company Websites by you and we will track their transactions. We reserve the right to refuse Customers (or to close their accounts) if necessary to comply with any requirements we may periodically establish.",
        thirdText:
          "4.3. We shall make available monitoring tools which enable you to monitor your Affiliate Account and the level of your Commission and the payment thereof.",
        fourthText:
          "4.4. We shall use and process the following personal data of an Affiliate or any Affiliate employee, as follows: your username for logging in, your email address, name, date of birth, your country and address, telephone number and financial data for the purposes of ensuring a high level of security, fulfilling the AML legal requirements and for managing our business relationship.",
        fifthText:
          "4.5. Subject to your strict adherence to the Affiliate Agreement, we shall pay you the Commission in accordance with Clause 6.",
      },
      five: {
        title: "5. COMPANY RIGHTS AND REMEDIES",
        firstText:
          "In the case of your breach (or, where relevant, suspected breach) of this Agreement or your negligence in performance under the Affiliate Program, or failure to meet your obligations hereunder, the Company shall have the following remedies available:",
        secondText:
          "a) the right to suspend your participation in the Affiliate Program for the period required to investigate any activities that may be in breach of the Affiliate Agreement. During such period of suspension payment of Commissions will also be suspended;",
        thirdText:
          "b) the right to withhold any Commission or any other payment to the Affiliate arising from or relating to any specific campaign, traffic, content or activity conducted or created by the Affiliate which is in breach of the Affiliate’s obligations under the Affiliate Agreement;",
        fourthText:
          "c) the right to withhold from the Commission monies which Company deems reasonable to cover any indemnity given by the Affiliate hereunder or to cover any liability of Company which arises as a result of the Affiliate’s breach of the Affiliate Agreement;",
        fifthText: "d) immediately terminate the Affiliate Agreement;",
        sixthText:
          "e) the right to withhold monies held in the Affiliate Wallet if they are not withdrawn within a period of 3 (three) months from the date of the termination of the Affiliate Agreement in accordance with clause 9.1;",
        seventhText:
          "f) the right not to pay the Affiliate's income if the Affiliate Program has suspicions or direct evidence that the Affiliate is bringing fake Customers;",
        eighthText:
          "g) the Company’s right to set up special terms of partnership for an Affiliate if the Customer comes by a brand name search or brand name traffic.",
        ninthText:
          "h) shall have right to change the Commission or Commission structure and can impose a fine on Affiliate who violates a treaty.",
        tenthText:
          "Our rights and remedies detailed above shall not be mutually exclusive.",
      },
      six: {
        title: "6. COMMISSION AND PAYMENT",
        firstText:
          "6.1. Subject to your adherence to the provisions of the Affiliate Agreement, you will earn Commission in accordance with the Commission Structure. We retain the right to change the Commission percentage and method of calculation of Commission in accordance with this clause.",
        secondText:
          "6.2 The Commission is calculated at the end of each month and payments shall be made on a monthly basis in arrears, not later than the 7th of the following calendar month. Payments via invoices are paid till 15th of the month for the previous payment period.",
        thirdText:
          "6.3 Reporting period time which is used by Affiliate Program for the calculation of earnings to the Affiliate is a calendar month.",
        fourthText:
          "6.4. Payment of Commission will be made through our Affiliate Wallet. Due to existing regulations, Affiliates may be required for verification and “know your customer” documentation before a withdrawal can be accessed.",
        fifthText:
          "6.5. A minimum amount of €25 may be withdrawn from the Affiliate Wallet at one time to the payment systems: Neteller, Skrill, CoinsPaid and a minimum amount of €300 may be withdrawn from the Affiliate Wallet at one time by Bank Transfer.",
        sixthText:
          "6.6. If an error is made in the calculation of the Commission, the Company has the right to correct such calculation at any time and will immediately pay out underpayment or reclaim overpayment made to the Affiliate.",
        seventhText:
          "6.7. The Affiliate may, at the Company’s sole discretion, be provided with the opportunity to restructure its commission structure.",
        eighthText:
          "6.8. The Affiliate’s acceptance of a Commission payment shall constitute the full and final settlement of the balance due for the relevant period. In case the Affiliate disagrees with the balance due as reported, he or she shall notify the Company within fourteen (14) calendar days after a reporting period and clearly state reasons of the disagreement. Failure to notify the Company within this time limit shall be considered as an irrevocable acknowledgment of the balance due for the relevant period, also Affiliate can not request any other additional information for this particular reporting period.",
        ninthText:
          "6.9. The Commission shall be deemed to be exclusive of value added tax or any other applicable tax. The Affiliate shall have the sole responsibility to pay any and all taxes, levies, charges and any other money payable or due to any tax authority, department or other competent entity as a result of the compensation generated under the Affiliate Agreement.",
        tenthText:
          "6.10. Interest rate will be paid to an Affiliate based on NGR. NGR stands for Net Gaming Revenue. It is calculated according to the following formula: Bets – Wins – Bonuses - Admin Fee.",
        eleventhText:
          "6.11. All commissions will be paid only to an active Customer which made a minimum or more than a minimum deposits to a Company’s website and do not have any restrictions on his account including gambling dependence or fraud activity.",
        twelfthText:
          "6.12. Payments to the Affiliate take place only via the payment systems, with which the Affiliate Program works. Full current list of supported payment systems you can find in your Affiliate Account.",
        thirteenthText:
          "6.13. If the total amount of player's bets is less than the amount of winnings and the casino bonuses, the Affiliate's income is negative and is equal to zero. The negative value of the Affiliate's income will not be transferred to the next month (unless otherwise agreed between the Affiliate and the Affiliate Program). A negative balance on one brand does not affect a positive balance on another brand. Payments are made for each brand separately and and they don’t co-relate with each other.",
        fourteenthText:
          "6.14. The Affiliate can involve sub-affiliate. In that case the Affiliate gets commission from the income of his sub-affiliate in the amount of 5 % from the total earnings of all attracted sub-affiliates. The sub-affiliate fee is calculated on the Affiliate’s balance in a similar way to the calculation of income from the attracted Customer.",
        fifteenthText:
          "6.15. Accrual and payments of the Partner’s income are possible only in Euro currency.",
      },
      seven: {
        title: "7. STANDARD COMMISSION STRUCTURES",
        subtitle: "Your percentage depends on last mont's FTD",
        firstText: "FTD 0 = 25% from NGR",
        secondText: "FTD 1-5 = 30% from NGR",
        thirdText: "FTD 6-10 = 35% from NGR",
        fourthText: "FTD 11-20 = 40% from NGR",
        fifthText: "FTD 21-30 = 45% of NGR",
        sixthText: "FTD 31 and more = 50% of NGR",
        seventhText: "FTD = First time deposits",
      },
      eight: {
        title: "8. CONFIDENTIAL INFORMATION",
        firstText:
          "During the term of the Affiliate Agreement, you may from time to time be entrusted with confidential information relating to our business, operations, or underlying technology and/or the Affiliate Program (including, for example, the Commissions earned by you under the Affiliate Program).",
        secondText:
          "You agree to avoid disclosure or unauthorized use of any such confidential information to third persons or outside parties unless you have our prior written consent. You also agree that you will use the confidential information only for the purposes of the Affiliate Agreement. Your obligations in regards to this clause survive the termination of this Agreement.",
        thirdText:
          "In addition, you must not issue any press release or similar communication to the public with respect to your participation in the Affiliate Program without the prior written consent of the Company (with approval of the exact content to also be approved by Company).",
      },
      nine: {
        title: "9. TERM AND TERMINATION",
        first: {
          title: "9.1. Term",
          firstText:
            "The terms of Affiliate agreement will tern into power when you are approved as an Affiliate our right after registration in Affiliate program and will be continuous unless and until either Party notifies the other in writing that it wishes to terminate the Agreement. In this case the Agreement will be terminated 30 days after such notice is given. For purposes of notification of termination, delivery via e-mail is considered a written and immediate form of notification.",
          secondText:
            "For the avoidance of doubt, Company may also terminate (in accordance with Clause 5 above) upon immediate notice at any time for the Affiliates failure to meet their obligations under the Agreement or otherwise for the Affiliate’s negligence.",
        },
        second: {
          title: "9.2. Affiliate actions upon termination",
          firstText:
            "Upon termination you must immediately remove all of Company banners or creatives from the Affiliate Website and disable all Affiliate Links from the Affiliate Website to all Company Websites.",
          secondText:
            "All rights and licenses given to you in the Affiliate Agreement shall immediately terminate.",
          thirdText:
            "You will return to Company any confidential information and all copies of it in your possession and control, and will cease all uses of all Company Intellectual Property Rights.",
        },
        third: {
          title: "9.3. Commission",
          text:
            "Upon termination of the Affiliate Agreement for any reason, all Commission relating to any Customers directed to Company during the term shall not be payable to the Affiliate as from the date of termination.",
        },
      },
      ten: {
        title: "10. MISCELLANEOUS",
        first: {
          title: "10.1. Disclaimer",
          text:
            "We make no express or implied warranties or representations with respect to the Affiliate Program, about Company or the Commission payment arrangements (including, without limitation, functionality, warranties of fitness, merchantability, legality or non-infringement). In addition, we make no representation that the operation of our sites will be uninterrupted or error-free and will not be liable for the consequences if there are any. In the event of a discrepancy between the reports offered in the Affiliate Account system and the Company database, the database shall be deemed accurate.",
        },
        second: {
          title: "10.2. Indemnity and Limitation of Liability",
          firstText:
            "You shall indemnify and hold Company, our directors, employees and representatives harmless from and against any and all liabilities, losses, damages and costs, including legal fees, resulting from or in any way connected with (a) any breach by you of any provision of the Affiliate Agreement, (b) the performance of your duties and obligations under the Affiliate Agreement, (c) your negligence or (d) any injury caused directly or indirectly by your negligent or intentional acts or omissions, or the unauthorized use of our creatives and links or this Affiliate Program.",
          secondText:
            "The Company shall not be held liable for any direct or indirect, special, or consequential damages (or any loss of revenue, profits, or data), any loss of goodwill or reputation arising in connection with the Affiliate Agreement or the Affiliate Program, even if we have been advised of the possibility of such damages.",
        },
        third: {
          title: "10.3. Non-Waiver",
          text:
            "Our failure to enforce your strict performance of any provision of the Affiliate Agreement will not constitute a waiver of our right to subsequently enforce such provision or any other provision of the Affiliate Agreement.",
        },
        fourth: {
          title: "10.4. Relationship of Parties",
          text:
            "The Company and the Affiliate are independent contractors and nothing in the Affiliate Agreement will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between us. You will have no authority to make or accept any offers or representations on our behalf. You will not make any statement, whether on your site or otherwise, that would contradict anything in this Affiliate Agreement.",
        },
        fifth: {
          title: "10.5. Force Majeure",
          text:
            "Neither party shall be liable to the other for any delay or failure to perform its obligations under the Affiliate Agreement if such delay or failure arises from a cause beyond its reasonable control, including but not limited to labour disputes, strikes, industrial disturbances, acts of God, acts of terrorism, floods, lightning, utility or communications failures, earthquakes or other casualty. If such event occurs, the non-performing Party is excused from whatever performance is prevented by the event to the extent prevented provided that if the force majeure event subsists for a period exceeding thirty (30) calendar days then either Party may terminate the Affiliate Agreement with immediate effect by providing a written notice.",
        },
        sixth: {
          title: "10.6. Assignability",
          text:
            "You may not assign the Affiliate Agreement, by operation of law or otherwise, without our prior written consent.",
        },
        seventh: {
          title: "10.7. Severability",
          text:
            "If any provision of the Affiliate Agreement is held to be invalid, illegal or unenforceable in any respect, such provision will be ineffective only to the extent of such invalidity, or unenforceability, without invalidating the remainder of the Affiliate Agreement or any provision hereof.",
        },
        eighth: {
          title: "10.8. English language",
          text:
            "The Affiliate Agreement was first drafted in English. Should there be any conflict or discrepancy between the English language version and any other language, the English version shall prevail.",
        },
        ninth: {
          title: "10.9. Modification of Terms & Conditions",
          firstText:
            "We may modify any of the terms and conditions contained in the Affiliate Agreement or replace it at any time and in our sole discretion by posting a change notice or a new agreement on our site. Modifications may include, for example, changes in the scope of available Commissions and Affiliate Program rules.",
          secondText:
            "If any modification is unacceptable to you, your need to terminate the Affiliate Agreement. Your continued participation in our Affiliate Program following our posting of a change notice or new agreement will constitute binding acceptance of the modification or of the new agreement.",
        },
      },
    },
  },
  generic: {
    locale: "English",
    login: "Log in",
    signup: "Sign up",
    becomeOurPartner: "Become our partner",
    commission: "Commission",
    brand: "Brand",
    faq: "FAQ",
    contactUs: "Contact us",
    tnc: "T&C",
  },
};
